### ISSUE TITLE
More/different solutions for the Day 2 optimization tasks

### ISSUE THREAD

**Issue by tmsmnchr** [crstnbr/JuliaNRW21#6]
My solutions for the optimization tasks. For the first one, I also precompute the sum as was mentioned during the meeting.

```julia
function work1!(A, b, c, N)
    D = sum(A)
    @. b = b*c*D
end

N = 100
A = rand(N,N)
b = rand(N)
bcopy = [ x for x in b ]
c = 1.23

@btime work1!($A, $b, $c, $N);
```

For the second one, I precompute a lookup table and transform the vector v to a fake matrix to enable element-wise operations.

```julia
struct Vecmat{T} <: AbstractMatrix{T}
    vec::Vector{T}
end

import Base
Base.getindex(x::Vecmat, i::Int, j::Int) = x.vec[i]
Base.size(x::Vecmat) = (length(x.vec), length(x.vec))

lookup = [ -cos(2*j) for j in 0:255 ]

function work2!(A, B, v, N)
    val = Vecmat([ lookup[mod(x,256)+1] for x in v])
    @. A = B * val
end

N = 4000
A = zeros(N,N)
B = rand(N,N)
v = rand(Int, N);

using BenchmarkTools
runtime = @belapsed work2!($A, $B, $v, $N);
perf = N*N*1e-6/runtime # MIt/s
println("Performance: $perf MIt/s")
```

I am a little confused that if I replace the line
```julia
@. A = B * val
```
by
```julia
@inbounds for j in 1:N
        for i in 1:N
            A[i,j] = B[i,j]*val[i,j];
        end
    end;
```
it is much, much slower (roughly 850 MIt/s to 8 MIt/s). Why is that? I thought, this would be roughly the same.

Did you guys find other improvements?

**Comment by svngross** [comment]
For exercise 1, I also moved the sum in front of the loop (which is mathematical equivalent, since c and b[i] are scalars):

```
function work3!(A, N, b, c)
    s= c*sum(A);
    for i in 1:N
        b[i] *= s;
    end
end
```
This is 1000x times faster than the original version on my machine, getting from 1.034 ms (502 allocations: 7.72 MiB) to 1.043 μs (0 allocations: 0 bytes).

**Comment by carstenbauer** [comment]
> Why is that? I thought, this would be roughly the same.

You have a small type instability in your function `work2!` (see the red color in the `@code_warntype` output). Sometimes it is (for some reason) hard for the compiler to infer the return type of a generator. However, this instability doesn't propagate far (because under the hood the `@.` magic calls into functions rather than directly translating the code into two for loops, so effectively we have a function barrier) and, thus, the instability doesn't matter much.

In the case with the explicit for loops however we don't have that barrier and the performance drops. (The situation is similar as in the "user input"/"reading data from disk" example discussed today.)

You can restore the performance, in fact improve it a bit (we have seen that explicit loops tend to be a little faster than broadcasting), by explicitly setting `Vecmat{Float64}` instead of just `Vecmat`:

```Julia
function work2_improved!(A, B, v, N)
    val = Vecmat{Float64}([ lookup[mod(x,256)+1] for x in v])
    @inbounds for j in 1:N
        for i in 1:N
            A[i,j] = B[i,j]*val[i,j];
        end
    end;
end
```

**Comparison on my machine:**

`work2!` with `@.` broadcasting:
```Julia
Performance: 928.4559684399247 MIt/s
```

`work2!` with loops:
```Julia
Performance: 9.599301142078954 MIt/s
```

`work2_improved!`, i.e. with loops but explicit `Vecmat{Float64}`:
```Julia
Performance: 1032.843253513055 MIt/s
```

Hope this helps!

**Comment by carstenbauer** [comment]
> ```julia
> import Base
> Base.getindex(x::Vecmat, i::Int, j::Int) = x.vec[i]
> Base.size(x::Vecmat) = (length(x.vec), length(x.vec))
> ```

Note that to add a method for `getindex` and `size` it is enough to **either**

```Julia
import Base: getindex, size
getindex(x::Vecmat, i::Int, j::Int) = x.vec[i]
size(x::Vecmat) = (length(x.vec), length(x.vec))
```

**or** (no `import Base` necessary)

```Julia
Base.getindex(x::Vecmat, i::Int, j::Int) = x.vec[i]
Base.size(x::Vecmat) = (length(x.vec), length(x.vec))
```

**Comment by tmsmnchr** [comment]
Ah, thanks a lot! Indeed, I forgot to set the specific type and was just lucky with the broadcasting due to the function barrier.

**Comment by carstenbauer** [comment]
@tmsmnchr Actually, the reason for why it is hard / impossible to figure out the return type of the generator is that your lookup table is a non-constant global variable. Hence its type can change at any point. Just making lookup a `const lookup` makes things behave like you expect.
